language: rust
dist: bionic
env:
  - RUST_BACKTRACE=1
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update && sudo apt-get install -y libdbus-1-dev pulseaudio rtkit ; fi
os:
  - linux
  - osx
  - windows
script:
  - cargo build --verbose
rust:
  - stable
  - beta
  - nightly
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
