language: rust
dist: bionic
env:
  - RUST_BACKTRACE=1
addons:
  apt:
    packages:
      - libdbus-1-dev
      - pulseaudio
os:
  - linux
  - osx
  - windows
rust:
  - stable
  - beta
  - nightly
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
