language: rust
addons:
  apt:
    packages:
      - libdbus-1-dev
os:
  - linux
  - osx
  - windows
rust:
  - stable
  - beta
  - nightly
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
